esphome:
  name: mintymcu_ir_tv
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  fast_connect: True
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_password

captive_portal:

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

remote_receiver:
    pin:
      number: D1
      inverted: True
      mode:
        input: true
        pullup: true
    dump: all

remote_transmitter:
  pin: D2
  # Infrared remotes use a 50% carrier signal
  carrier_duty_percent: 50%

switch:
  # Speakers
  - platform: template
    name: "Speakers Power"
    id: speakers_power
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x807F
          command: 0x827D
      - binary_sensor.template.publish:
          id: sensor_trigger_speakers_power
          state: ON
      - delay: 1s
      - switch.turn_off: speakers_power
    turn_off_action:
      - binary_sensor.template.publish:
          id: sensor_trigger_speakers_power
          state: OFF
  - platform: template
    name: "Speakers Volume Up"
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x807F
          command: 0x906F
  - platform: template
    name: "Speakers Volume Down"
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x807F
          command: 0xA05F



  # HDMI Switch
  #
  - platform: template
    name: "HDMI 2.1 Power"
    id: hdmi2_1_power
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0xFE01
          command: 0xE01F
  - platform: template
    name: "HDMI 2.1 A-B"
    id: hdmi2_1_ab
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0xFE01
          command: 0xE21D
  - platform: template
    name: "HDMI 2.1 ARC On/Off"
    id: hdmi_2_1_arc_on_off
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0xFE01
          command: 0xA35C
  - platform: template
    name: "HDMI 2.1 Audio Passthrough"
    id: hdmi2_1_audio_passthrough
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0xFE01
          command: 0xE41B
  - platform: template
    name: "HDMI 2.1 Audio 2-channel"
    id: hdmi2_1_audio_2ch
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0xFE01
          command: 0xE51A
  - platform: template
    name: "HDMI 2.1 Audio 5.1-channel"
    id: hdmi2_1_audio_5_1ch
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0xFE01
          command: 0xE11E
  - platform: template
    name: "HDMI 2.1 OUT A Channel 1"
    id: hdmi2_1_out_a_channel_1
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0xFE01
          command: 0xFD02
  - platform: template
    name: "HDMI 2.1 OUT A Channel 2"
    id: hdmi2_1_out_a_channel_2
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0xFE01
          command: 0xF20D
  - platform: template
    name: "HDMI 2.1 OUT A Channel 3"
    id: hdmi2_1_out_a_channel_3
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0xFE01
          command: 0xED12
  - platform: template
    name: "HDMI 2.1 OUT A Channel 4"
    id: hdmi2_1_out_a_channel_4
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0xFE01
          command: 0xEE11
  - platform: template
    name: "HDMI 2.1 OUT A On/Off"
    id: hdmi2_1_out_a_on_off
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0xFE01
          command: 0xEF10
  - platform: template
    name: "HDMI 2.1 OUT B Channel 1"
    id: hdmi2_1_out_b_channel_1
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0xFE01
          command: 0xF10E
  - platform: template
    name: "HDMI 2.1 OUT B Channel 2"
    id: hdmi2_1_out_b_channel_2
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0xFE01
          command: 0xF30C
  - platform: template
    name: "HDMI 2.1 OUT B Channel 3"
    id: hdmi2_1_out_b_channel_3
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0xFE01
          command: 0xF609
  - platform: template
    name: "HDMI 2.1 OUT B Channel 4"
    id: hdmi2_1_out_b_channel_4
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0xFE01
          command: 0xFA05
  - platform: template
    name: "HDMI 2.1 OUT B On/Off"
    id: hdmi2_1_out_b_on_off
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0xFE01
          command: 0xFE01

sensor:
  - platform: wifi_signal
    name: "MintyMCU_IR_TV WiFi Signal Sensor"
    update_interval: 60s
  - platform: uptime
    name: "MintyMCU_IR_TV Uptime Sensor"
    update_interval: 60s
    filters:
      - lambda: return x / (24 * 3600);
    unit_of_measurement: "days"

binary_sensor:
    - platform: status
      name: "MintyMCU_IR_TV Status"
    - platform: template
      name: "MintyMCU_IR_TV Power Trigger Sensor"
      id: sensor_trigger_speakers_power

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "MintyMCU_IR_TV IP Address"
    ssid:
      name: "MintyMCU_IR_TV Connected SSID"
    bssid:
      name: "MintyMCU_IR_TV Connected BSSID"
  - platform: version
    name: "MintyMCU_IR_TV ESPHome Version"

# secret: !include secrets.yaml