esphome:
  name: mintymcu_ir_beam
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  fast_connect: True
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_password

captive_portal:

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password


remote_transmitter:
  pin: D2
  # Infrared remotes use a 50% carrier signal
  carrier_duty_percent: 50%

switch:
  - platform: template
    name: "Onkyo Power"
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x4B36D32C
          nbits: 32
  - platform: template
    name: "Onkyo Volume Up"
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x4BB640BF
          nbits: 32
  - platform: template
    name: "Onkyo Volume Down"
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x4BB6C03F
          nbits: 32
  - platform: template
    name: "Onkyo Volume Mute"
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x4BB6A05F
          nbits: 32
  - platform: template
    name: "Onkyo Mode Movie"
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x4B350BF4
          nbits: 32
  - platform: template
    name: "Onkyo Mode Music"
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x4B358B74
          nbits: 32
  - platform: template
    name: "Onkyo Mode Game"
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x4B354BB4
          nbits: 32
  - platform: template
    name: "Onkyo OUT TV/CD"
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x4BB6906F
          nbits: 32
  - platform: template
    name: "Onkyo OUT GAME"
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x4BB6B04F
          nbits: 32

  - platform: template
    name: "LG Air Power On"
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x08800448
          nbits: 28
  - platform: template
    name: "LG Air Power Off"
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x088C0051
          nbits: 28
  - platform: template
    name: "LG Air Intensive Mode On"
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x08810089
          nbits: 28
  - platform: template
    name: "LG Air Intensive Mode Off"
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x0880834F
          nbits: 28
  - platform: template
    name: "LG Air Swing"
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x08810001
          nbits: 28
  - platform: template
    name: "LG Air Temp 20"
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x08808541
          nbits: 28
  - platform: template
    name: "LG Air Temp 21"
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x08808642
          nbits: 28
  - platform: template
    name: "LG Air Temp 22"
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x08808743
          nbits: 28
  - platform: template
    name: "LG Air Temp 23"
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x08808844
          nbits: 28
  - platform: template
    name: "LG Air Temp 24"
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x08808945
          nbits: 28
  - platform: template
    name: "LG Air Temp 25"
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x08808A46
          nbits: 28

  - platform: template
    name: "LG Air Fan Speed 1"
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x08808800
          nbits: 28
  - platform: template
    name: "LG Air Fan Speed 2"
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x08808822
          nbits: 28
  - platform: template
    name: "LG Air Fan Speed 3"
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x08808844
          nbits: 28
  - platform: template
    name: "LG Air Night Mode 1hr"
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x088A03C9
          nbits: 28
  - platform: template
    name: "LG Air Night Mode 2hr"
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x088A0789
          nbits: 28

  - platform: template
    name: "LG Air Night Mode 4hr"
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x088A0F09
          nbits: 28
  - platform: template
    name: "LG Air Night Mode Off"
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x088A000A
          nbits: 28
  

  # System
  - platform: restart
    name: "MintyMCU_IR_Beam Restart"

sensor:
  - platform: wifi_signal
    name: "MintyMCU_IR_Beam WiFi Signal Sensor"
    update_interval: 60s
  - platform: uptime
    name: "MintyMCU_IR_Beam Uptime Sensor"
    update_interval: 60s
    filters:
      - lambda: return x / (24 * 3600);
    unit_of_measurement: "days"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "MintyMCU_IR_Beam IP Address"
    ssid:
      name: "MintyMCU_IR_Beam Connected SSID"
    bssid:
      name: "MintyMCU_IR_Beam Connected BSSID"
  - platform: version
    name: "MintyMCU_IR_Beam ESPHome Version"

climate:
  - platform: climate_ir_lg       # adjust to match your AC unit!
    name: "Room AC"

# secret: !include secrets.yaml