esphome:
  name: mintymcu_ir
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

remote_receiver:
    pin:
      number: D1
      inverted: True
    dump: all

remote_transmitter:
  pin: D2
  # Infrared remotes use a 50% carrier signal
  carrier_duty_percent: 50%

switch:
  # Speakers
  - platform: template
    name: "Speakers Power"
    id: speakers_power
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x807F
          command: 0x827D
      - binary_sensor.template.publish:
          id: sensor_trigger_speakers_power
          state: ON
      - delay: 1s
      - switch.turn_off: speakers_power
    turn_off_action:
      - binary_sensor.template.publish:
          id: sensor_trigger_speakers_power
          state: OFF
  - platform: template
    name: "Speakers Mute"
    id: speakers_mute
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x807F
          command: 0x20DF
      - binary_sensor.template.publish:
          id: sensor_trigger_speakers_mute
          state: ON
      - delay: 1s
      - switch.turn_off: speakers_mute
    turn_off_action:
      - binary_sensor.template.publish:
          id: sensor_trigger_speakers_mute
          state: OFF
  - platform: template
    name: "Speakers Volume Up"
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x807F
          command: 0x906F
  - platform: template
    name: "Speakers Volume Down"
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x807F
          command: 0xA05F
  # HDMI Switch
#  - platform: template
#    name: "HDMI Power On"
#    id: hdmi_power_on
#    turn_on_action:
#      - remote_transmitter.transmit_nec:
#          address: 0x807F
#          command: 0x3AC5
#  - platform: template
#    name: "HDMI Power Off"
#    id: hdmi_power_off
#    turn_on_action:
#      - remote_transmitter.transmit_nec:
#          address: 0x807F
#          command: 0xF807
#  - platform: template
#    name: "HDMI Channel 1"
#    id: hdmi_channel_1
#    turn_on_action:
#      - remote_transmitter.transmit_nec:
#          address: 0x807F
#          command: 0xD827
#  - platform: template
#    name: "HDMI Channel 2"
#    id: hdmi_channel_2
#    turn_on_action:
#      - remote_transmitter.transmit_nec:
#          address: 0x807F
#          command: 0x58A7
#  - platform: template
#    name: "HDMI Channel 3"
#    id: hdmi_channel_3
#    turn_on_action:
#      - remote_transmitter.transmit_nec:
#          address: 0x807F
#          command: 0x40BF
#  - platform: template
#    name: "HDMI Channel 4"
#    id: hdmi_channel_4
#    turn_on_action:
#      - remote_transmitter.transmit_nec:
#          address: 0x807F
#          command: 0xB04F
#  - platform: template
#    name: "HDMI Audio On/Off"
#    id: hdmi_audio_on_off
#    turn_on_action:
#      - remote_transmitter.transmit_nec:
#          address: 0x807F
#          command: 0x708F
#  - platform: template
#    name: "HDMI Auto Turn On/Off"
#    id: hdmi_auto_turn_on_off
#    turn_on_action:
#      - remote_transmitter.transmit_nec:
#          address: 0x807F
#          command: 0xF00F
  # System
  - platform: restart
    name: "MintyMCU_IR Restart"

sensor:
  - platform: wifi_signal
    name: "MintyMCU_IR WiFi Signal Sensor"
    update_interval: 60s
  - platform: uptime
    name: "MintyMCU_IR Uptime Sensor"
    update_interval: 60s
    filters:
      - lambda: return x / (24 * 3600);
    unit_of_measurement: "days"

binary_sensor:
    - platform: status
      name: "MintyMCU_IR Status"
    - platform: template
      name: "MintyMCU_IR Volume Mute Trigger Sensor"
      id: sensor_trigger_speakers_mute
    - platform: template
      name: "MintyMCU_IR Power Trigger Sensor"
      id: sensor_trigger_speakers_power

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "MintyMCU_IR IP Address"
    ssid:
      name: "MintyMCU_IR Connected SSID"
    bssid:
      name: "MintyMCU_IR Connected BSSID"
  - platform: version
    name: "MintyMCU_IR ESPHome Version"

# secret: !include secrets.yaml