esphome:
  name: mintymcu_ir
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  fast_connect: True
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_password

captive_portal:

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

remote_receiver:
    pin:
      number: D1
      inverted: True
    dump: all

remote_transmitter:
  pin: D2
  # Infrared remotes use a 50% carrier signal
  carrier_duty_percent: 50%

switch:
  # Speakers
  - platform: template
    name: "Speakers Power"
    id: speakers_power
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x807F
          command: 0x827D
      - binary_sensor.template.publish:
          id: sensor_trigger_speakers_power
          state: ON
      - delay: 1s
      - switch.turn_off: speakers_power
    turn_off_action:
      - binary_sensor.template.publish:
          id: sensor_trigger_speakers_power
          state: OFF
  - platform: template
    name: "Speakers Mute"
    id: speakers_mute
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x807F
          command: 0x20DF
      - binary_sensor.template.publish:
          id: sensor_trigger_speakers_mute
          state: ON
      - delay: 1s
      - switch.turn_off: speakers_mute
    turn_off_action:
      - binary_sensor.template.publish:
          id: sensor_trigger_speakers_mute
          state: OFF
  - platform: template
    name: "Speakers Volume Up"
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x807F
          command: 0x906F
  - platform: template
    name: "Speakers Volume Down"
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x807F
          command: 0xA05F

  # Speakers - Other commands
  #
  # - platform: template
  #   name: "Speakers Input"
  #   turn_on_action:
  #     - remote_transmitter.transmit_nec:
  #         address: 0x807F
  #         command: 0x629D
  # - platform: template
  #   name: "Speakers Save"
  #   turn_on_action:
  #     - remote_transmitter.transmit_nec:
  #         address: 0x807F
  #         command: 0xA25D
  # - platform: template
  #   name: "Speakers Sleep"
  #   turn_on_action:
  #     - remote_transmitter.transmit_nec:
  #         address: 0x807F
  #         command: 0x22DD
  - platform: template
    name: "Speakers Treble Up"
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x807F
          command: 0x12ED
  - platform: template
    name: "Speakers Treble Down"
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x807F
          command: 0x52AD
  #
  # Never used this five commands
  #
  # - platform: template
  #   name: "Speakers CH Up"
  #   turn_on_action:
  #     - remote_transmitter.transmit_nec:
  #         address: 0x807F
  #         command: 0x32CD
  # - platform: template
  #   name: "Speakers CH Down"
  #   turn_on_action:
  #     - remote_transmitter.transmit_nec:
  #         address: 0x807F
  #         command: 0x728D
  # - platform: template
  #   name: "Speakers Tune Up"
  #   turn_on_action:
  #     - remote_transmitter.transmit_nec:
  #         address: 0x807F
  #         command: 0x926D
  # - platform: template
  #   name: "Speakers Tune Down"
  #   turn_on_action:
  #     - remote_transmitter.transmit_nec:
  #         address: 0x807F
  #         command: 0xB04F
  # - platform: template
  #   name: "Speakers Auto"
  #   turn_on_action:
  #     - remote_transmitter.transmit_nec:
  #         address: 0x807F
  #         command: 0xB24D
  - platform: template
    name: "Speakers Bass Up"
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x807F
          command: 0x30CF
  - platform: template
    name: "Speakers Bass Down"
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x807F
          command: 0xF00F
  - platform: template
    name: "Speakers Subwoofer Up"
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x807F
          command: 0xD02F
  - platform: template
    name: "Speakers Subwoofer Down"
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x807F
          command: 0xE01F
  # 
  # I think i don't need this enabled all time
  # But will keep here in case of circumstances
  #
  # - platform: template
  #   name: "Speakers Set"
  #   turn_on_action:
  #     - remote_transmitter.transmit_nec:
  #         address: 0x807F
  #         command: 0x50AF
  # - platform: template
  #   name: "Speakers Clock"
  #   turn_on_action:
  #     - remote_transmitter.transmit_nec:
  #         address: 0x807F
  #         command: 0x609F
  # - platform: template
  #   name: "Speakers Number 1"
  #   turn_on_action:
  #     - remote_transmitter.transmit_nec:
  #         address: 0x807F
  #         command: 0x4AB5
  # - platform: template
  #   name: "Speakers Number 2"
  #   turn_on_action:
  #     - remote_transmitter.transmit_nec:
  #         address: 0x807F
  #         command: 0x8A75
  # - platform: template
  #   name: "Speakers Number 3"
  #   turn_on_action:
  #     - remote_transmitter.transmit_nec:
  #         address: 0x807F
  #         command: 0x0AF5
  # - platform: template
  #   name: "Speakers Number 4"
  #   turn_on_action:
  #     - remote_transmitter.transmit_nec:
  #         address: 0x807F
  #         command: 0xE817
  # - platform: template
  #   name: "Speakers Number 5"
  #   turn_on_action:
  #     - remote_transmitter.transmit_nec:
  #         address: 0x807F
  #         command: 0x6897
  # - platform: template
  #   name: "Speakers Number 6"
  #   turn_on_action:
  #     - remote_transmitter.transmit_nec:
  #         address: 0x807F
  #         command: 0xA857
  # - platform: template
  #   name: "Speakers Number 7"
  #   turn_on_action:
  #     - remote_transmitter.transmit_nec:
  #         address: 0x807F
  #         command: 0x6A95
  # - platform: template
  #   name: "Speakers Number 8"
  #   turn_on_action:
  #     - remote_transmitter.transmit_nec:
  #         address: 0x807F
  #         command: 0xAA55
  # - platform: template
  #   name: "Speakers Number 9"
  #   turn_on_action:
  #     - remote_transmitter.transmit_nec:
  #         address: 0x807F
  #         command: 0x2AD5
  # - platform: template
  #   name: "Speakers Number 0"
  #   turn_on_action:
  #     - remote_transmitter.transmit_nec:
  #         address: 0x807F
  #         command: 0x9A65
  # - platform: template
  #   name: "Speakers Repeat"
  #   turn_on_action:
  #     - remote_transmitter.transmit_nec:
  #         address: 0x807F
  #         command: 0x5AA5
  # - platform: template
  #   name: "Speakers Reset"
  #   turn_on_action:
  #     - remote_transmitter.transmit_nec:
  #         address: 0x807F
  #         command: 0x1AE5

  # HDMI Switch
  #
  - platform: template
    name: "HDMI Power On"
    id: hdmi_power_on
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x807F
          command: 0x3AC5
  - platform: template
    name: "HDMI Power Off"
    id: hdmi_power_off
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x807F
          command: 0xF807
  - platform: template
    name: "HDMI Channel 1"
    id: hdmi_channel_1
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x807F
          command: 0xD827
  - platform: template
    name: "HDMI Channel 2"
    id: hdmi_channel_2
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x807F
          command: 0x58A7
  - platform: template
    name: "HDMI Channel 3"
    id: hdmi_channel_3
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x807F
          command: 0x40BF
  - platform: template
    name: "HDMI Channel 4"
    id: hdmi_channel_4
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x807F
          command: 0xB04F
  - platform: template
    name: "HDMI Audio On/Off"
    id: hdmi_audio_on_off
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x807F
          command: 0x708F
  - platform: template
    name: "HDMI Audio Passthrough"
    id: hdmi_audio_passthrough
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x807F
          command: 0x08F7
  - platform: template
    name: "HDMI ARC On/Off"
    id: hdmi_arc_on_off
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x807F
          command: 0x30CF
  - platform: template
    name: "HDMI Auto Turn On/Off"
    id: hdmi_auto_turn_on_off
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x807F
          command: 0xF00F

  # SPDIF Switch
  #
  # * A outputs to Bluetooth transmitter
  # * B outputs to DAC
  #
  - platform: template
    name: "SPDIF Power On"
    id: spdif_power_on
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x01FE
          command: 0x58A7
  - platform: template
    name: "SPDIF Bluetooth 1"
    id: spdif_bluetooth_1
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x01FE
          command: 0x807F
  - platform: template
    name: "SPDIF Bluetooth Raspberry"
    id: spdif_bluetooth_raspberry
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x01FE
          command: 0x20DF
  - platform: template
    name: "SPDIF Bluetooth Extractor"
    id: spdif_bluetooth_extractor
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x01FE
          command: 0xE01F
  - platform: template
    name: "SPDIF Bluetooth HDMI"
    id: spdif_bluetooth_hdmi
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x01FE
          command: 0x50AF
  - platform: template
    name: "SPDIF DAC 1"
    id: spdif_dac_1
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x01FE
          command: 0xC03F
  - platform: template
    name: "SPDIF DAC Raspberry"
    id: spdif_dac_raspberry
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x01FE
          command: 0x609F
  - platform: template
    name: "SPDIF DAC Extractor"
    id: spdif_dac_extractor
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x01FE
          command: 0x906F
  - platform: template
    name: "SPDIF DAC HDMI"
    id: spdif_dac_hdmi
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x01FE
          command: 0xF807
  # System
  - platform: restart
    name: "MintyMCU_IR Restart"

sensor:
  - platform: wifi_signal
    name: "MintyMCU_IR WiFi Signal Sensor"
    update_interval: 60s
  - platform: uptime
    name: "MintyMCU_IR Uptime Sensor"
    update_interval: 60s
    filters:
      - lambda: return x / (24 * 3600);
    unit_of_measurement: "days"

binary_sensor:
    - platform: status
      name: "MintyMCU_IR Status"
    - platform: template
      name: "MintyMCU_IR Volume Mute Trigger Sensor"
      id: sensor_trigger_speakers_mute
    - platform: template
      name: "MintyMCU_IR Power Trigger Sensor"
      id: sensor_trigger_speakers_power

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "MintyMCU_IR IP Address"
    ssid:
      name: "MintyMCU_IR Connected SSID"
    bssid:
      name: "MintyMCU_IR Connected BSSID"
  - platform: version
    name: "MintyMCU_IR ESPHome Version"

# secret: !include secrets.yaml